// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RackConfigurationn.Repositories;

#nullable disable

namespace RackConfigurationn.Server.Migrations
{
    [DbContext(typeof(RepositoryContext))]
    [Migration("20251221122439_AddUserTable")]
    partial class AddUserTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RackConfigurationn.Shared.Models.Component", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ComponentId")
                        .HasColumnType("int");

                    b.Property<string>("DeckType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeck")
                        .HasColumnType("bit");

                    b.Property<string>("Material")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("MaxLoadCapacity")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ComponentId");

                    b.ToTable("Components");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Upright",
                            IsDeck = false,
                            Material = "Çelik",
                            MaxLoadCapacity = 1000.0,
                            Name = "Ana Dikme (3.5m)"
                        },
                        new
                        {
                            Id = 2,
                            Category = "Upright",
                            IsDeck = false,
                            Material = "Çelik",
                            MaxLoadCapacity = 1000.0,
                            Name = "Yan Dikme (3.5m)"
                        },
                        new
                        {
                            Id = 30,
                            Category = "Upright",
                            IsDeck = false,
                            Material = "Çelik",
                            MaxLoadCapacity = 800.0,
                            Name = "Ana Dikme (2m)"
                        },
                        new
                        {
                            Id = 31,
                            Category = "Upright",
                            IsDeck = false,
                            Material = "Çelik",
                            MaxLoadCapacity = 800.0,
                            Name = "Yan Dikme (2m)"
                        },
                        new
                        {
                            Id = 32,
                            Category = "Upright",
                            IsDeck = false,
                            Material = "Çelik",
                            MaxLoadCapacity = 900.0,
                            Name = "Ana Dikme (2.5m)"
                        },
                        new
                        {
                            Id = 33,
                            Category = "Upright",
                            IsDeck = false,
                            Material = "Çelik",
                            MaxLoadCapacity = 900.0,
                            Name = "Yan Dikme (2.5m)"
                        },
                        new
                        {
                            Id = 34,
                            Category = "Upright",
                            IsDeck = false,
                            Material = "Çelik",
                            MaxLoadCapacity = 1000.0,
                            Name = "Ana Dikme (3m)"
                        },
                        new
                        {
                            Id = 35,
                            Category = "Upright",
                            IsDeck = false,
                            Material = "Çelik",
                            MaxLoadCapacity = 1000.0,
                            Name = "Yan Dikme (3m)"
                        },
                        new
                        {
                            Id = 3,
                            Category = "Beam",
                            IsDeck = false,
                            Material = "Çelik",
                            MaxLoadCapacity = 500.0,
                            Name = "Kiriş (220cm)"
                        },
                        new
                        {
                            Id = 4,
                            Category = "Beam",
                            IsDeck = false,
                            Material = "Çelik",
                            MaxLoadCapacity = 250.0,
                            Name = "Kiriş (110cm)"
                        },
                        new
                        {
                            Id = 5,
                            Category = "Panel",
                            DeckType = "With wooden deck",
                            IsDeck = true,
                            Material = "Ahşap",
                            MaxLoadCapacity = 300.0,
                            Name = "Ahşap Kapak"
                        },
                        new
                        {
                            Id = 6,
                            Category = "Panel",
                            DeckType = "With steel deck",
                            IsDeck = true,
                            Material = "Çelik",
                            MaxLoadCapacity = 350.0,
                            Name = "Çelik Kapak"
                        },
                        new
                        {
                            Id = 7,
                            Category = "Panel",
                            DeckType = "With galvanised mesh deck",
                            IsDeck = true,
                            Material = "Galvaniz",
                            MaxLoadCapacity = 400.0,
                            Name = "Galvanizli Izgara"
                        },
                        new
                        {
                            Id = 8,
                            Category = "Panel",
                            DeckType = "Inclined deck",
                            IsDeck = true,
                            Material = "Çelik",
                            MaxLoadCapacity = 100.0,
                            Name = "Eğimli Kapak"
                        },
                        new
                        {
                            Id = 9,
                            Category = "Panel",
                            DeckType = "Multiplex board",
                            IsDeck = true,
                            Material = "Kompozit",
                            MaxLoadCapacity = 300.0,
                            Name = "Multiplex Pano"
                        },
                        new
                        {
                            Id = 10,
                            Category = "Panel",
                            DeckType = "Without layers",
                            IsDeck = true,
                            Material = "Yok",
                            MaxLoadCapacity = 0.0,
                            Name = "Katman Yok"
                        });
                });

            modelBuilder.Entity("RackConfigurationn.Shared.Models.ComponentPrice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ComponentId")
                        .HasColumnType("int");

                    b.Property<int?>("Depth")
                        .HasColumnType("int");

                    b.Property<DateTime>("EffectiveDate")
                        .HasColumnType("datetime2");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("ComponentId");

                    b.ToTable("ComponentPrices");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ComponentId = 1,
                            EffectiveDate = new DateTime(2025, 10, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 55.0
                        },
                        new
                        {
                            Id = 2,
                            ComponentId = 2,
                            EffectiveDate = new DateTime(2025, 10, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 50.0
                        },
                        new
                        {
                            Id = 30,
                            ComponentId = 30,
                            EffectiveDate = new DateTime(2025, 10, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 35.0
                        },
                        new
                        {
                            Id = 31,
                            ComponentId = 31,
                            EffectiveDate = new DateTime(2025, 10, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 30.0
                        },
                        new
                        {
                            Id = 32,
                            ComponentId = 32,
                            EffectiveDate = new DateTime(2025, 10, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 42.0
                        },
                        new
                        {
                            Id = 33,
                            ComponentId = 33,
                            EffectiveDate = new DateTime(2025, 10, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 38.0
                        },
                        new
                        {
                            Id = 34,
                            ComponentId = 34,
                            EffectiveDate = new DateTime(2025, 10, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 48.0
                        },
                        new
                        {
                            Id = 35,
                            ComponentId = 35,
                            EffectiveDate = new DateTime(2025, 10, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 44.0
                        },
                        new
                        {
                            Id = 3,
                            ComponentId = 3,
                            EffectiveDate = new DateTime(2025, 10, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 30.0
                        },
                        new
                        {
                            Id = 4,
                            ComponentId = 4,
                            EffectiveDate = new DateTime(2025, 10, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 15.0
                        },
                        new
                        {
                            Id = 5,
                            ComponentId = 5,
                            Depth = 40,
                            EffectiveDate = new DateTime(2025, 10, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 18.0
                        },
                        new
                        {
                            Id = 6,
                            ComponentId = 5,
                            Depth = 50,
                            EffectiveDate = new DateTime(2025, 10, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 22.0
                        },
                        new
                        {
                            Id = 7,
                            ComponentId = 5,
                            Depth = 60,
                            EffectiveDate = new DateTime(2025, 10, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 26.0
                        },
                        new
                        {
                            Id = 8,
                            ComponentId = 5,
                            Depth = 80,
                            EffectiveDate = new DateTime(2025, 10, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 34.0
                        },
                        new
                        {
                            Id = 9,
                            ComponentId = 5,
                            Depth = 100,
                            EffectiveDate = new DateTime(2025, 10, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 42.0
                        },
                        new
                        {
                            Id = 10,
                            ComponentId = 5,
                            Depth = 120,
                            EffectiveDate = new DateTime(2025, 10, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 50.0
                        },
                        new
                        {
                            Id = 11,
                            ComponentId = 6,
                            Depth = 40,
                            EffectiveDate = new DateTime(2025, 10, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 25.0
                        },
                        new
                        {
                            Id = 12,
                            ComponentId = 6,
                            Depth = 50,
                            EffectiveDate = new DateTime(2025, 10, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 30.0
                        },
                        new
                        {
                            Id = 13,
                            ComponentId = 6,
                            Depth = 60,
                            EffectiveDate = new DateTime(2025, 10, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 35.0
                        },
                        new
                        {
                            Id = 14,
                            ComponentId = 6,
                            Depth = 80,
                            EffectiveDate = new DateTime(2025, 10, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 45.0
                        },
                        new
                        {
                            Id = 15,
                            ComponentId = 6,
                            Depth = 100,
                            EffectiveDate = new DateTime(2025, 10, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 55.0
                        },
                        new
                        {
                            Id = 16,
                            ComponentId = 6,
                            Depth = 120,
                            EffectiveDate = new DateTime(2025, 10, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 65.0
                        },
                        new
                        {
                            Id = 17,
                            ComponentId = 7,
                            Depth = 60,
                            EffectiveDate = new DateTime(2025, 10, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 35.0
                        },
                        new
                        {
                            Id = 18,
                            ComponentId = 7,
                            Depth = 80,
                            EffectiveDate = new DateTime(2025, 10, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 45.0
                        },
                        new
                        {
                            Id = 19,
                            ComponentId = 7,
                            Depth = 120,
                            EffectiveDate = new DateTime(2025, 10, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 65.0
                        },
                        new
                        {
                            Id = 20,
                            ComponentId = 8,
                            EffectiveDate = new DateTime(2025, 10, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 22.0
                        },
                        new
                        {
                            Id = 21,
                            ComponentId = 9,
                            EffectiveDate = new DateTime(2025, 10, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 28.0
                        },
                        new
                        {
                            Id = 22,
                            ComponentId = 10,
                            EffectiveDate = new DateTime(2025, 10, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 0.0
                        });
                });

            modelBuilder.Entity("RackConfigurationn.Shared.Models.Deck", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DeckType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ShelfUnitId")
                        .HasColumnType("int");

                    b.Property<int>("level")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ShelfUnitId");

                    b.ToTable("Decks");
                });

            modelBuilder.Entity("RackConfigurationn.Shared.Models.DeckOption", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DeckType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Depth")
                        .HasColumnType("float");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("DeckOptions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DeckType = "Without layers",
                            Depth = 40.0,
                            ImageUrl = "/imagesdecktypes/withoutlayers.jpg"
                        },
                        new
                        {
                            Id = 2,
                            DeckType = "With wooden deck",
                            Depth = 40.0,
                            ImageUrl = "/imagesdecktypes/woodendeck.jpg"
                        },
                        new
                        {
                            Id = 3,
                            DeckType = "With steel deck",
                            Depth = 40.0,
                            ImageUrl = "/imagesdecktypes/steeldeck.jpg"
                        },
                        new
                        {
                            Id = 4,
                            DeckType = "Without layers",
                            Depth = 50.0,
                            ImageUrl = "/imagesdecktypes/withoutlayers.jpg"
                        },
                        new
                        {
                            Id = 5,
                            DeckType = "With wooden deck",
                            Depth = 50.0,
                            ImageUrl = "/imagesdecktypes/woodendeck.jpg"
                        },
                        new
                        {
                            Id = 6,
                            DeckType = "With steel deck",
                            Depth = 50.0,
                            ImageUrl = "/imagesdecktypes/steeldeck.jpg"
                        },
                        new
                        {
                            Id = 7,
                            DeckType = "Without layers",
                            Depth = 60.0,
                            ImageUrl = "/imagesdecktypes/withoutlayers.jpg"
                        },
                        new
                        {
                            Id = 8,
                            DeckType = "With wooden deck",
                            Depth = 60.0,
                            ImageUrl = "/imagesdecktypes/woodendeck.jpg"
                        },
                        new
                        {
                            Id = 9,
                            DeckType = "With steel deck",
                            Depth = 60.0,
                            ImageUrl = "/imagesdecktypes/steeldeck.jpg"
                        },
                        new
                        {
                            Id = 10,
                            DeckType = "With galvanised mesh deck",
                            Depth = 60.0,
                            ImageUrl = "/imagesdecktypes/galvaniseddeck.jpg"
                        },
                        new
                        {
                            Id = 11,
                            DeckType = "Inclined deck",
                            Depth = 60.0,
                            ImageUrl = "/imagesdecktypes/inclineddeck.jpg"
                        },
                        new
                        {
                            Id = 12,
                            DeckType = "Multiplex board",
                            Depth = 60.0,
                            ImageUrl = "/imagesdecktypes/multiplexdeck.jpg"
                        },
                        new
                        {
                            Id = 13,
                            DeckType = "Without layers",
                            Depth = 80.0,
                            ImageUrl = "/imagesdecktypes/withoutlayers.jpg"
                        },
                        new
                        {
                            Id = 14,
                            DeckType = "With wooden deck",
                            Depth = 80.0,
                            ImageUrl = "/imagesdecktypes/woodendeck.jpg"
                        },
                        new
                        {
                            Id = 15,
                            DeckType = "With steel deck",
                            Depth = 80.0,
                            ImageUrl = "/imagesdecktypes/steeldeck.jpg"
                        },
                        new
                        {
                            Id = 16,
                            DeckType = "With galvanised mesh deck",
                            Depth = 80.0,
                            ImageUrl = "/imagesdecktypes/galvaniseddeck.jpg"
                        },
                        new
                        {
                            Id = 17,
                            DeckType = "Inclined deck",
                            Depth = 80.0,
                            ImageUrl = "/imagesdecktypes/inclineddeck.jpg"
                        },
                        new
                        {
                            Id = 18,
                            DeckType = "Multiplex board",
                            Depth = 80.0,
                            ImageUrl = "/imagesdecktypes/multiplexdeck.jpg"
                        },
                        new
                        {
                            Id = 19,
                            DeckType = "Without layers",
                            Depth = 100.0,
                            ImageUrl = "/imagesdecktypes/withoutlayers.jpg"
                        },
                        new
                        {
                            Id = 20,
                            DeckType = "With wooden deck",
                            Depth = 100.0,
                            ImageUrl = "/imagesdecktypes/woodendeck.jpg"
                        },
                        new
                        {
                            Id = 21,
                            DeckType = "With steel deck",
                            Depth = 100.0,
                            ImageUrl = "/imagesdecktypes/steeldeck.jpg"
                        },
                        new
                        {
                            Id = 22,
                            DeckType = "Without layers",
                            Depth = 120.0,
                            ImageUrl = "/imagesdecktypes/withoutlayers.jpg"
                        },
                        new
                        {
                            Id = 23,
                            DeckType = "With wooden deck",
                            Depth = 120.0,
                            ImageUrl = "/imagesdecktypes/woodendeck.jpg"
                        },
                        new
                        {
                            Id = 24,
                            DeckType = "With steel deck",
                            Depth = 120.0,
                            ImageUrl = "/imagesdecktypes/steeldeck.jpg"
                        },
                        new
                        {
                            Id = 25,
                            DeckType = "With galvanised mesh deck",
                            Depth = 120.0,
                            ImageUrl = "/imagesdecktypes/galvaniseddeck.jpg"
                        });
                });

            modelBuilder.Entity("RackConfigurationn.Shared.Models.Rack", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<double>("Depth")
                        .HasColumnType("float");

                    b.Property<bool>("IsAddOnRack")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDoubleSided")
                        .HasColumnType("bit");

                    b.Property<double>("TotalHeight")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Racks");
                });

            modelBuilder.Entity("RackConfigurationn.Shared.Models.ShelfUnit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Depth")
                        .HasColumnType("int");

                    b.Property<double>("Height")
                        .HasColumnType("float");

                    b.Property<int>("NumberOfDecks")
                        .HasColumnType("int");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("int");

                    b.Property<int>("RackId")
                        .HasColumnType("int");

                    b.Property<double>("UnitWidth")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("RackId");

                    b.ToTable("ShelfUnits");
                });

            modelBuilder.Entity("RackConfigurationn.Shared.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("User");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "admin@rack.com",
                            FirstName = "Sistem",
                            LastName = "Yöneticisi",
                            Password = "123",
                            Role = "Admin",
                            Username = "admin"
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2025, 2, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "ceren@rack.com",
                            FirstName = "Ceren",
                            LastName = "Öztürk",
                            Password = "password",
                            Role = "Customer",
                            Username = "ceren"
                        });
                });

            modelBuilder.Entity("RackConfigurationn.Shared.Models.Component", b =>
                {
                    b.HasOne("RackConfigurationn.Shared.Models.Component", null)
                        .WithMany("Prices")
                        .HasForeignKey("ComponentId");
                });

            modelBuilder.Entity("RackConfigurationn.Shared.Models.ComponentPrice", b =>
                {
                    b.HasOne("RackConfigurationn.Shared.Models.Component", "Component")
                        .WithMany()
                        .HasForeignKey("ComponentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Component");
                });

            modelBuilder.Entity("RackConfigurationn.Shared.Models.Deck", b =>
                {
                    b.HasOne("RackConfigurationn.Shared.Models.ShelfUnit", "ShelfUnit")
                        .WithMany("Decks")
                        .HasForeignKey("ShelfUnitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ShelfUnit");
                });

            modelBuilder.Entity("RackConfigurationn.Shared.Models.ShelfUnit", b =>
                {
                    b.HasOne("RackConfigurationn.Shared.Models.Rack", "Rack")
                        .WithMany("ShelfUnits")
                        .HasForeignKey("RackId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rack");
                });

            modelBuilder.Entity("RackConfigurationn.Shared.Models.Component", b =>
                {
                    b.Navigation("Prices");
                });

            modelBuilder.Entity("RackConfigurationn.Shared.Models.Rack", b =>
                {
                    b.Navigation("ShelfUnits");
                });

            modelBuilder.Entity("RackConfigurationn.Shared.Models.ShelfUnit", b =>
                {
                    b.Navigation("Decks");
                });
#pragma warning restore 612, 618
        }
    }
}
